version: '3'
services: 
  consul:
    container_name: consul
    image: consul:latest
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    command: |
      sh -c 'set -uex; \
        consul agent -server -bootstrap-expect=1 -data-dir /consul/data -node=agent-one -enable-script-checks=true -ui -disable-host-node-id -client 0.0.0.0 & \
        sleep 20 && \
        consul kv import @/consul/Centralization-Configuration-Consul/oauth2.json && \
        consul kv import @/consul/Centralization-Configuration-Consul/apigateway.json && \
        tail -f /dev/null'
    volumes: 
      - '/tmp/consul_data_1:/consul/data'
      - './Centralization-Configuration-Consul:/consul/Centralization-Configuration-Consul'
    networks: 
      main:
        aliases: 
          - consul

  postgresqldb:
    container_name: postgresqldb
    image: rizkimufrizal/postgresql
    environment:
      - POSTGRES_MULTIPLE_DATABASES="db_oauth2_server","db_analytics"
      - POSTGRES_USER=postgresqldb
      - POSTGRES_PASSWORD=postgresqldb
    ports:
      - "5432:5432"
    networks:
      main:
        aliases:
          - postgresqldb

  redissessionoauth2:
    container_name: redissessionoauth2
    command: redis-server --requirepass redissessionoauth2
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      main:
        aliases: 
          - redissessionoauth2

networks: 
  main: